variables:
  - name: IDAM_VERSION
    description: "The version of the idam package to build and deploy"
    # x-release-please-start-version
    default: 0.1.16
    # x-release-please-end

tasks:
  - name: build-package
    actions:
      - description: "Build IDAM ZARF Package"
        cmd: zarf package create idam/ --architecture amd64 --confirm --no-progress --output build/

  - name: deploy-package
    actions:
      - description: "Deploy the IDAM ZARF Package"
        cmd: zarf package deploy build/zarf-package-uds-idam-*.tar.zst --confirm

  - name: build-bundle-dependencies
    actions:
      - description: "Build IDAM Postgres Dependency"
        cmd: zarf package create pkg-deps/postgres --confirm --no-progress --output build/

  - name: build-bundle
    actions:
      - description: "Build IDAM Bundle (IDAM Package and IDAM Dependencies)"
        cmd: export IDAM_VERSION=${IDAM_VERSION} && cat dev/idam/uds-bundle.yaml.tmpl | envsubst > dev/idam/uds-bundle.yaml && uds create dev/idam/ --confirm --no-progress

  - name: deploy-bundle
    actions:
      - description: "Deploy the uds-idam and dependencies bundle"
        cmd: uds deploy dev/idam/uds-bundle-uds-core-idam-amd64-0.0.1.tar.zst --confirm

  - name: build-published-bundle
    actions:
      - description: "Remove Existing uds-idam Package"
        cmd: rm -f build/zarf-package-uds-idam-amd64-*.tar.zst 2> /dev/null || true

      - description: "Pull the Published uds-idam Package"
        cmd: zarf package pull oci://ghcr.io/defenseunicorns/uds-capability/uds-idam:${IDAM_VERSION}-amd64 -o build/
