application:
  name: keycloak
  createNamespace: ###ZARF_VAR_KEYCLOAK_CREATE_NAMESPACE###
  namespace: keycloak
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/keycloak.git
  ref:
    tag: 18.4.3-bb.1
  values: |
    ###ZARF_VAR_KEYCLOAK_VALUES###
  dependsOn:
    ###ZARF_VAR_KEYCLOAK_DEPENDS_ON###