apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../idam/keycloak-ingress
patches:
  - patch: |-
      - op: add
        path: /spec/components/ingressGateways/0/k8s
        value:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "###ZARF_VAR_PRIVATE_KEYCLOAK_LB###"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    target:
      group: install.istio.io
      version: v1alpha1
      kind: IstioOperator
