application:
  name: keycloak
  namespace: keycloak
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/keycloak.git
  tag: 18.4.3-bb.1
  values: |
    ###ZARF_VAR_KEYCLOAK_VALUES###