# apiVersion: v1
# kind: Service
# metadata:
#   name: keycloak-postgresql
#   namespace: keycloak
# spec:
#   type: ExternalName
#   externalName: postgresql.keycloak.svc.cluster.local



#  WARNING  Unable to complete helm chart install/upgrade, waiting 10 seconds and trying again: failed                                                                                 
#           to create resource: admission webhook "pepr-uds-core.pepr.dev" denied the request:
#           ExternalName services are not allowed.