extraInitContainers: |-
  - name: plugin
    image: registry1.dso.mil/ironbank/big-bang/p1-keycloak-plugin:3.2.1
    imagePullPolicy: Always
    command:
    - sh
    - -c
    - |
      cp /app/p1-keycloak-plugin.jar /init
      ls -l /init
    volumeMounts:
    - name: plugin
      mountPath: "/init"
  - name: extra-jar
    image: defenseunicorns/extra-jar:0.0.1
    imagePullPolicy: Always
    command:
    - sh
    - -c
    - |
      cp /app/extra.jar /init
      ls -l /init
    volumeMounts:
    - name: extra
      mountPath: "/init"
extraVolumeMounts: |-
  - name: certauthority
    mountPath: /etc/x509/https/cas.pem
    subPath: cas.pem
    readOnly: true
  - name: customreg
    mountPath: /opt/jboss/keycloak/customreg.yaml
    subPath: customreg.yaml
    readOnly: true
  - name: plugin
    mountPath: /opt/keycloak/providers/p1-keycloak-plugin.jar
    subPath: p1-keycloak-plugin.jar
  - name: quarkusproperties
    mountPath: /opt/keycloak/conf/quarkus.properties
    subPath: quarkus.properties
  - name: realm
    mountPath: /opt/keycloak/data/import/realm.json
    subPath: realm.json
  - name: truststore
    mountPath: /opt/keycloak/conf/truststore.jks
    subPath: truststore.jks
  - name: extra
    mountPath: /opt/keycloak/providers/extra.jar
    subPath: extra.jar
extraVolumes: |-
  - name: certauthority
    secret:
      secretName: {{ include "keycloak.fullname" . }}-certauthority
  - name: plugin
    emptyDir: {}
  - name: quarkusproperties
    secret:
      secretName: {{ include "keycloak.fullname" . }}-quarkusproperties
      defaultMode: 0777
  - name: realm
    secret:
      secretName: {{ include "keycloak.fullname" . }}-realm
  - name: customreg
    secret:
      secretName: {{ include "keycloak.fullname" . }}-customreg
  - name: truststore
    secret:
      secretName: {{ include "keycloak.fullname" . }}-truststore
  - name: extra
    emptyDir: {}