name: Test UDS IDAM

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          download-init-package: true

      - name: Create Cluster and Deploy IDAM
        run: uds run cluster-full

      - name: Teardown k3d cluster
        if: always()
        run: k3d cluster delete uds
