name: Publish UDS IDAM Theme Image

# Will remove before merge and make it only tags
on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Theme Image 
        run: make push
        working-directory: theme
        timeout-minutes: 60
