name: build-and-publish

concurrency:
    cancel-in-progress: true
    group: build-and-publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Init zarf cache
        uses: actions/cache@v3
        with:
          path: "~/.zarf-cache"
          key: zarf-cache

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.28.3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}

      - name: Build keycloak package
        run: zarf package create idam --confirm --no-progress

      - name: Publish keycloak package
        run: zarf package publish zarf-package-uds-idam-amd64-*.tar.zst oci://ghcr.io/defenseunicorns/uds-capability --no-progress

      - name: Publish keycloak skeleton
        run: zarf package publish idam oci://ghcr.io/defenseunicorns/uds-capability --no-progress
