name: Publish UDS Package

on:
  push:
    branches:
      - main

jobs:
  tag-new-version:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-flag.outputs.release_created }}
    steps:
      - name: Create Release Tag
        id: tag
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest # use configs in release-please-config.json
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> $GITHUB_OUTPUT 

  publish-idam-package:
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true'}}
    uses: ./.github/workflows/publish.uds.package.yaml
    with:
      working_dir: idam
    secrets: inherit

  publish-idam-aws:
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true'}}
    uses: ./.github/workflows/publish.dubbd.package.yaml
    with:
      working_dir: aws
    secrets: inherit