name: Test UDS IDAM Upgrade 

on:
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/create-zarf-package
        with:
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          working-dir: idam
          download-init-package: true

      - name: Create k3d cluster
        id: create-cluster
        # renovate: datasource=github-tags depName=defenseunicorns/uds-aws-ci-k3d versioning=semver
        uses: defenseunicorns/uds-aws-ci-k3d@v0.0.5
        with:
          cluster-action: create
          aws-assume-role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          aws-region: us-west-2

      - name: Install uds-cli
        uses: supplypike/setup-bin@v3
        with:
          # renovate: uds-cli-uri datasource=github-tags depName=defenseunicorns/uds-cli
          uri: 'https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.5-alpha/uds-cli_v0.0.5-alpha_Linux_amd64 '
          name: 'uds'
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: 'v0.0.5-alpha'

      # Build Env Setup Bundle (Metallb, DUBBD, POSTGRES, Source IDAM, Published IDAM)
      - name: Build bundle with published IDAM
        run: make build/published

      # Deploy IdAM Published Bundle 
      - name: Deploy CI Upgrade Test Published IDAM
        run: make deploy/bundle

      - name: Build bundle with source IDAM
        run: make build/all

      # Deploy IdAM Source Bundle
      - name: Deploy source IDAM bundle
        run: make deploy/bundle

      - name: Teardown k3d cluster
        if: always()
        # renovate: datasource=github-tags depName=defenseunicorns/uds-aws-ci-k3d versioning=semver
        uses: defenseunicorns/uds-aws-ci-k3d@v0.0.5
        with:
          cluster-action: destroy