name: Test Upgrade UDS IDAM

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          download-init-package: true

      - name: Setup K3d Cluster and Dubbd K3d package
        run: uds run cluster-create

      - name: Build and Deploy Published IDAM Bundle
        run: uds run ci-upgrade-test

      - name: Build and Deploy Source IDAM Bundle
        run: uds run deploy-idam

      - name: Teardown k3d cluster
        if: always()
        run: k3d cluster delete uds
